eos_default_login: "admin"
eos_default_password: "123456"
eos_login: admin
eos_password: 123456
eos_root_user: root
eos_root_password: 123456

junos_default_login: "root"
junos_default_password:  ""
junos_login: "root"
junos_password: ""

cisco_default_login: "root"
cisco_default_password: ""
cisco_login: "root"
cisco_password: ""


sonic_login: "cisco"
sonic_default_passwords:
 - "cisco123"
sonic_password: "cisco123"
sonicadmin_user: "cisco"
sonicadmin_password: "cisco123"

k8s_master_login: "ubuntu"
k8s_master_password: "use_own_value"

ptf_host_user: root
ptf_host_pass: root

vm_host_user: sonic
vm_host_password: roZes@123
vm_host_become_password: roZes@123
