---

- conf-name: sfd-vt2
  group-name: sfd-vt2
  topo: t2
  ptf_image_name: docker-ptf
  ptf: ptf_vt2
  ptf_ip: 1.72.33.204/16
  ptf_ipv6: fc0b::1/64
  server: server_1
  vm_base: VM0100
  dut:
    - sfd-vt2-lc0
    - sfd-vt2-lc1
    - sfd-vt2-lc2
    - sfd-vt2-sup
  inv_name: lab
  auto_recover: 'True'
  comment: Tests SFD T2 - Vanguard setup
